kind: pipeline
name: default

steps:
  - name: test
    image: golang:${GO_VERSION}
    commands:
      - go test

matrix:
  GO_VERSION:
    - "1.16"

trigger:
  branch:
    - master
  event:
    - pull_request
