language: go

# have the docker service set up (we'll update it later)
services:
  - docker

matrix:
  include:
    - go: 1.13.x
    - go: 1.12.x
      env: STABLE=true

env:
  global:
    - IMAGE=$TRAVIS_REPO_SLUG
    - VERSION=$TRAVIS_TAG
#    - GO111MODULE=on

install:
  - go get -v ./...

# first execute the test suite.
# after the test execution is done and didn't
# fail, build the images (if this step fails
# the whole Travis build is considered a failure).
script:
  - env
  - make test

deploy:
  - provider: script
    skip_cleanup: true
    script: make image-release
    on:
      tags: true
      condition: $STABLE = true